import numpy as np
import pandas as pd
from scipy.spatial import distance_matrix
from multiprocessing import Pool
import os
import glob

from Bio.PDB import PDBParser, PDBIO, Structure, Model

from utils import run_subprocess
from pdb_utils import Parser

from typing import Dict, Iterator

from create_plots import create_plot_from_dict


class Assay():
	def __init__( self, sys_name: str, base_dir, cores: int, prec: int, 
						ensmeble_file: str, output_dir: str ):
		self.sys_name = "2ayo"
		self.base_dir = base_dir
		self.cores = 5
		self.chain_break_threshold = 4.0
		self.prec = 4
		self.ensmeble_file = ensmeble_file
		
		self.output_dir = output_dir
		self.analysis_dir = os.path.join( self.output_dir, "analysis" )
		
		self.parser = Parser( self.ensmeble_file )

		self.full_val_dict = {}
		self.full_val_dict_file = os.path.join( self.analysis_dir, "full_validation_dict.npy" )
		self.full_val_plot_file = os.path.join( self.analysis_dir, "full_validation_plots.png" )
		self.full_val_csv = os.path.join( self.analysis_dir, "full_validation_plots.csv" )

		self.selected_val_dict = {}
		self.selected_val_dict_file = os.path.join( self.analysis_dir, "selected_validation_dict.npy" )
		self.selected_val_plot_file = os.path.join( self.analysis_dir, "selected_validation_plots.png" )
		self.selected_val_csv = os.path.join( self.analysis_dir, "selected_validation_plots.csv" )



	def forward( self ):
		# idx = 0
		# chain_breaks_dict = {}
		# for coords_dict in self.parser.get_coordinates():
		# 	chain_breaks_dict[idx] = self.get_chain_breaks( coords_dict )
		# 	idx += 1

		# self.quantify_chain_breaks( chain_breaks_dict )
		self.create_required_dir()
		if not os.path.exists( self.full_val_dict_file ):
			self.parallelize_validation_pipeline()
			np.save( self.full_val_dict_file, self.full_val_dict )
		else:
			self.full_val_dict = np.load( self.full_val_dict_file, allow_pickle = True ).item()

		self.filter_models()

		self.plot()

		self.write_to_csv()

		self.remove_tmp_dir()



	def create_required_dir( self ):
		"""
		Create the following directories:
			analysis
				tmp
		Temporary directory is used for storing the intermediate files 
			from running Molprobity validation.
		"""
		if not os.path.exists( self.analysis_dir ):
			os.makedirs( self.analysis_dir )

		self.tmp_dir = os.path.join( self.analysis_dir, "tmp" )
		if not os.path.exists( self.tmp_dir ):
			os.makedirs( self.tmp_dir )



	def remove_tmp_dir( self ):
		cmd = ["rm", "-r", f"{self.tmp_dir}"]
		run_subprocess( cmd )



	def write_model_to_pdb( self, model_id: str, model: Model, model_file: str ):
		"""
		Write a model to PDB file.
		Required to run Molprobity on all models separately.
		"""
		io = PDBIO()

		struct = Structure.Structure( f"Model_{model_id}" )
		struct.add( model )

		io.set_structure( struct )
		io.save( model_file )



	def validation_pipeline( self, entry ):
		"""
		Compute the no. of chain breaks.
		Perform Molprobity validation.
		"""
		model_id, model = list( entry )
		model_file = os.path.join( self.tmp_dir, f"{self.sys_name}_{model_id}.pdb" )
		molprob_output_dir = os.path.join( self.tmp_dir, f"molprob_{self.sys_name}_{model_id}" )

		self.write_model_to_pdb( model_id, model, model_file )

		self.run_molprobity( model_file, molprob_output_dir )
		summary_dict = self.get_molprobity_validation_summary( molprob_output_dir )
		summary_dict.update( {"model_id": model_id} )

		files_to_remove = glob.glob( f"{molprob_output_dir}*" )
		cmd = ["rm", "-r"] + files_to_remove
		run_subprocess( cmd )

		return summary_dict



	def parallelize_validation_pipeline( self ):
		"""
		Parse all models in parallel and perform all the required validations.
		"""
		structure = self.parser.structure
		model_ids = self.parser.get_model_ids()

		with Pool( self.cores ) as p:
			for result in p.imap_unordered( self.validation_pipeline, zip( model_ids, structure ) ):
				summary_dict = result

				for k, v in summary_dict.items():
					self.full_val_dict.setdefault( k, [] ).append( v )



	def get_molprobity_validation_summary( self, output_dir: str ):
		"""
		Molprobity can provide detailed information about:
			Ramachandran outliers
						favored
			Rotamer outliers
			C-beta deviations
			Clashscore
			RMS(bonds)
			RMS(angles)
			MolProbity score
			Resolution
			R-work
			R-free
			Refinement program
		All this can be obtained from the *.out file generated by molprobity.
		"""
		with open( f"{output_dir}.out", "r" ) as f:
			summary = f.readlines()

		summary_dict = {}
		for i in range( len( summary ) ):
			line = summary[i]
			if "Summary" in line:
				for j in range( i+1, len( summary ) ):
					l = summary[j]

					split_line = l.strip().split( " = " )
					if len( split_line ) < 2:
						continue

					key, value = split_line 
					key = "".join( key.split( "  " ) )
					value = "".join( value.split( "  " ) )

					# Remove spaces from the end.
					key = key[:-1] if key[-1] == " " else key
					# Remove '%' symbols.
					value = value.replace( "%", "" )
					
					if value.isalpha():
						summary_dict[key] = value
					else:
						summary_dict[key] = float( value )

		return summary_dict



	def run_molprobity( self, model_file: str, output_dir: str ) -> None:
		"""
		Run Molprobity validation using Phenix.
		requires a PDB file with just 1 model.
		Generates the following files:
			{prefix}_coot.py  {prefix}.out  {prefix}.pkl  {prefix}.txt

		output_dir --> must be in the format "/path/prefix".
			where path is the output directory path and prefix is the 
				name for the output files generated.
		"""
		molprob_cmd = [
						"phenix.molprobity",
						f"{model_file}",
						f"output.prefix={output_dir}"
						]

		run_subprocess( molprob_cmd )



	def filter_models( self ):
		"""
		Here we use the Molprobity score as a criterion for assessing model quality.
		Select the good scoring models.
		"""

		selected_models = self.get_good_models()

		for model_id in self.full_val_dict["model_id"]:
			if model_id in selected_models:
				for k, v in self.full_val_dict.items():
					self.selected_val_dict.setdefault( k, [] ).append( v )



	def get_good_models( self ):
		"""
		To filter out bad models we consider the median Molprobity score.
			Median because mean is sensitive to outliers.
		We remove models with a Molprobity score higher than 2*MAD (median absolute deviation).
		"""
		molprob_scores = self.full_val_dict["MolProbity score"]

		median_score = np.median( molprob_scores )

		# Compute the abolsute deviations from the median.
		abs_dev = np.abs( molprob_scores - median_score )
		mad = np.median( abs_dev )

		selected_models = []
		for i in range( len( molprob_scores ) ):
			model_id = self.full_val_dict["model_id"]

			# Calculate the lower and upper median bounds.
			lb = median_score - 2*mad
			ub = median_score + 2*mad

			if molprob_scores[i] >= lb and molprob_scores[i] <= ub:
				selected_models.append( model_id )

		return selected_models



	def write_to_csv( self ):
		"""
		Write validation dicts to csv file.
		"""
		df = pd.DataFrame()
		for k, v in self.full_val_dict.items():
			df[k] = v
		df.to_csv( self.full_val_csv, index = False )

		df = pd.DataFrame()
		for k, v in self.selected_val_dict.items():
			df[k] = v

		df.to_csv( self.selected_val_csv, index = False )


	def plot( self ):
		tmp_dict = self.full_val_dict.copy()
		_ = tmp_dict.pop( "model_id", None )
		create_plot_from_dict( tmp_dict, self.full_val_plot_file )

		tmp_dict = self.selected_val_dict.copy()
		_ = tmp_dict.pop( "model_id", None )
		create_plot_from_dict( tmp_dict, self.selected_val_plot_file )




	# def get_distance_matrix( self, coords1: np.array, coords2: np.array ):
	# 	"""
	# 	Calculate Ca distance matrix.
	# 	"""
	# 	return distance_matrix( coords1, coords2 )



	# def get_chain_breaks( self, coords_dict: Dict[str, np.array] ):
	# 	"""
	# 	Given the coordinates for all chains in a model, calculate the Ca-Ca chain breaks.
	# 	A chain break is identified if Ca-Ca distance between consecutive residues is >5 Angstrom.
	# 	"""
	# 	chain_breaks_dict = {}
	# 	for chain in coords_dict.keys():
	# 		if chain not in chain_breaks_dict.keys():
	# 			chain_breaks_dict[chain] = {"breaks": [], # np.array( coords.shape[0] )
	# 										"total_bonds": 0}
	# 		coords = coords_dict[chain]

	# 		dist_mat = self.get_distance_matrix( coords, coords )

	# 		for i in range( coords.shape[0] - 1 ):
	# 			j = i + 1
	# 			if dist_mat[i, j] > self.chain_break_threshold:
	# 				chain_breaks_dict[chain]["breaks"].append( ( i, j, round( dist_mat[i, j], self.prec ) ) )
	# 			chain_breaks_dict[chain]["total_bonds"] += 1

	# 	return chain_breaks_dict



	# def quantify_chain_breaks( self, chain_breaks_dict ):
	# 	"""
	# 	Calculate global and samplewise average for the fraction of chain breaks.
	# 	"""
	# 	global_avg = 0
	# 	global_breaks = 0
	# 	total_bonds = 0
	# 	samplewise_avg = np.array( [] )

	# 	for model in chain_breaks_dict.keys():
	# 		samplewise_breaks = 0
	# 		for chain in chain_breaks_dict[model]:
	# 			num_breaks = len( chain_breaks_dict[model][chain]["breaks"] )
	# 			samplewise_breaks += num_breaks
	# 			global_breaks += num_breaks
	# 			total_bonds += chain_breaks_dict[model][chain]["total_bonds"]
	# 		samplewise_avg = np.append( samplewise_avg, samplewise_breaks )

	# 	print( global_breaks, "  ", total_bonds )
	# 	global_avg = round( global_breaks/total_bonds, self.prec )
	# 	samplewise_avg = round( np.mean( samplewise_avg ), self.prec )

	# 	print( global_avg, "  ", samplewise_avg )



if __name__ == "__main__":
	Assay().forward()

