name: af_im 
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia 
dependencies:
  - python=3.10
  - libgcc=7.2
  - setuptools=59.5.0
  - pip
  - openmm==7.7
  - pdbfixer==1.8.1
  - pytorch-lightning==2.4.0
  - biopython==1.84
  - numpy==1.26.4
  - pandas=2.2.2
  - PyYAML==5.4.1
  - requests==2.32.3
  - tqdm==4.62.2
  - typing-extensions==4.12.2
  - wandb==0.16.6
  - modelcif==0.7
  - awscli==2.18.16
  - ml-collections==0.1.1
  - mkl=2022.1
  - aria2
  - git
  - bioconda::hmmer
  - bioconda::mmseqs2
  - bioconda::hhsuite
  - bioconda::kalign2
  - pytorch::pytorch=2.1
  - pytorch::pytorch-cuda=12.1
  - pip:
      - matplotlib==3.10.6
      - seaborn==0.13.2
      - scikit-learn==1.7.2
      - scipy==1.14.1
      - wget==3.2
      - aiohttp==3.13.2
      - DockQ==2.1.3
      - dm-tree==0.1.6
