"""
This module contains wrapper classes for using MolProbity.
Run MolProbity and provide the validation output.
"""
from typing import List, Tuple, Dict
import os
from ml_collections import ConfigDict
from multiprocessing import Pool

from utils.utils import run_subprocess

class Molprobity():
	"""
	Perform Molprobity validation on the input models.
	"""
	def __init__( self,
				sys_name: str,
				model_ids: int,
				cores: int,
				struct_format: str,
				molprob_config: ConfigDict,
				analysis_dir: str,
				relax_ensemble_dir: str,
				unrelax_ensemble_dir: str ):
		self.sys_name = sys_name
		# Identifier for a model.
		self.model_ids = model_ids
		self.cores = cores
		self.struct_format = struct_format
		self.molprob_config = molprob_config
		self.analysis_dir = analysis_dir
		# Dit containing PDB files for the relaxed models.
		self.relax_ensemble_dir = relax_ensemble_dir
		# Dit containing PDB files for the unrelaxed models.
		self.unrelax_ensemble_dir = unrelax_ensemble_dir
		# Dict to store Molprobity validation metrics.
		self.molprob_dict = {}


	def forward( self ):
		"""
		"""
		self.create_tmp_dir()
		self.run_molprobity_in_parallel()
		if self.molprob_config.clean_up:
			self.remove_tmp_dir()


	def create_tmp_dir( self ):
		"""
		Temporary directory is used for storing the intermediate files
			from running Molprobity validation.
		"""
		# Temporary directory is used for storing the intermediate files
		self.tmp_dir = os.path.join( self.analysis_dir, "molprob_tmp" )
		os.makedirs( self.tmp_dir, exist_ok = True )


	def remove_tmp_dir( self ):
		cmd = ["rm", "-r", f"{self.tmp_dir}"]
		run_subprocess( command = cmd )


	def get_model_file( self, model_id: int ):
		"""
		Return path to the model file.
		"""
		relax_model_file = os.path.join(
			self.relax_ensemble_dir,
			f"model_{model_id}.{self.struct_format}" )
		unrelax_model_file = os.path.join(
			self.unrelax_ensemble_dir,
			f"model_{model_id}.{self.struct_format}" )
		return relax_model_file, unrelax_model_file


	def get_molprob_tmp_out_dir( self, model_id: int ):
		"""
		Return the path for a tmp dir to store
			Molprobity output for a given model.
		"""
		relax_molprob_output_dir = os.path.join(
			self.tmp_dir,
			f"relax_molprob_{self.sys_name}_{model_id}" )
		unrelax_molprob_output_dir = os.path.join(
			self.tmp_dir,
			f"unrelax_molprob_{self.sys_name}_{model_id}" )
		return relax_molprob_output_dir, unrelax_molprob_output_dir

	################################################################################
	################################################################################
	def run_molprobity_in_parallel( self ):
		"""
		Perfom Molprobity validation on the given set of models in parallel.
		"""
		with Pool( self.cores ) as p:
			for result in p.imap_unordered( self.validate, self.model_ids ):
				summary_dict = result

				self.molprob_dict.update( summary_dict )


	def validate( self, model_id: int ) -> Dict[int, Dict[str, float]]:
		"""
		Perform Molprobity validation.
		Get the Molprobity metrics.
		"""
		relax_model_file, unrelax_model_file = self.get_model_file( model_id = model_id )
		( relax_molprob_output_dir,
			unrelax_molprob_output_dir ) = self.get_molprob_tmp_out_dir( model_id = model_id )

		self.run_molprobity( model_file = model_file,
							output_dir = molprob_output_dir )

		summary_dict = {
			model_id: {
				"relaxed": self.get_molprobity_validation_summary( relax_molprob_output_dir ),
				"unrelaxed": self.get_molprobity_validation_summary( unrelax_molprob_output_dir )
			}
		}

		# files_to_remove = glob.glob( f"{molprob_output_dir}*" )
		# cmd = ["rm", "-r"] + files_to_remove
		# run_subprocess( command = cmd )

		return summary_dict


	def run_molprobity( self, model_file: str, output_dir: str ):
		"""
		Run Molprobity validation using Phenix.
		requires a PDB file with just 1 model.
		Generates the following files:
			{prefix}_coot.py  {prefix}.out  {prefix}.pkl  {prefix}.txt

		output_dir --> must be in the format "/path/prefix".
			where path is the output directory path and prefix is the 
				name for the output files generated.
		"""
		molprob_cmd = [
						"phenix.molprobity",
						f"{model_file}",
						f"output.prefix={output_dir}"
						]

		run_subprocess( command = molprob_cmd )


	def get_molprobity_validation_summary( self, output_dir: str
										) -> Dict[str, float]:
		"""
		Molprobity can provide detailed information about:
			Ramachandran outliers
						favored
			Rotamer outliers
			C-beta deviations
			Clashscore
			RMS(bonds)
			RMS(angles)
			MolProbity score
			Resolution
			R-work
			R-free
			Refinement program
		All this can be obtained from the *.out file generated by molprobity.
		"""
		with open( f"{output_dir}.out", "r" ) as f:
			summary = f.readlines()

		summary_dict = {}
		for i in range( len( summary ) ):
			line = summary[i]
			if "Summary" in line:
				for j in range( i+1, len( summary ) ):
					l = summary[j]

					split_line = l.strip().split( " = " )
					if len( split_line ) < 2:
						continue

					key, value = split_line 
					key = "".join( key.split( "  " ) )
					value = "".join( value.split( "  " ) )

					# Remove spaces from the end.
					key = key[:-1] if key[-1] == " " else key
					# Remove '%' symbols.
					value = value.replace( "%", "" )
					
					if value.isalpha():
						summary_dict[key] = value
					else:
						summary_dict[key] = float( value )

		return summary_dict
