"""
This module contains wrapper classes for using MolProbity.
Run MolProbity for and provide the validation output.
"""

class Molprobity():
	"""
	Perform Molprobity validation on the input models.
	"""
	def __init__( self, sys_name: str, model_ids: int, base_dir: str, model_dir: str ):
		self.sys_name = sys_name
		# Path to the Molprobity dir.
		self.molprob_dir = os.path.join( base_dir, "molprobity_output" )
		# Dit containing PDB files for models.
		self.model_dir = model_dir
		# Identifier for a model.
		self.model_ids = model_ids
		# Dict to store Molprobity validation metrics.
		self.molprob_val_dict = {}
		# Note the time taken.
		self.time_file = os.path.join( self.molprob_dir, "Time_taken_molprob.txt" )


	def forward( self ):
		"""
		"""
		# Do not redo molprobity validation if already done.
		# 	Using the time_file as a marker.
		if not os.path.exists( self.time_file ):
			tic = time.time()
			# Create a temporary dir to store output files.
			self.create_dir()

			self.parallelize_molprobity_validation()
			toc = time.time()

			fh = open_file_handler( self.time_file, "w" )
			fh.writelines( f"Time taken: {( toc-tic )/3600} hours OR {( toc-tic )/60} minutes" )
		else:
			print( "Molprobity validation already done..." )


	def create_dir( self ):
		"""
		Temporary directory is used for storing the intermediate files
			from running Molprobity validation.
		"""
		if not os.path.exists( self.molprob_dir ):
			os.makedirs( self.molprob_dir )

		self.tmp_dir = os.path.join( self.molprob_dir, "tmp" )
		if not os.path.exists( self.tmp_dir ):
			os.makedirs( self.tmp_dir )


	def remove_tmp_dir( self ):
		cmd = ["rm", "-r", f"{self.tmp_dir}"]
		run_subprocess( cmd )


	def validate( self, model_id: int ) -> Dict[str, float]:
		"""
		Perform Molprobity validation.
		Get the Molprobity metrics.
		"""
		# model_file = os.path.join( self.ensmeble_dir, f"model_{model_id}_relaxed.pdb" )
		model_file = os.path.join( self.model_dir, f"model_{model_id}.pdb" )
		molprob_output_dir = os.path.join( self.tmp_dir, f"molprob_{self.sys_name}_{model_id}" )

		self.run_molprobity( model_file, molprob_output_dir )
		summary_dict = {}
		summary_dict[model_id] = self.get_molprobity_validation_summary( molprob_output_dir )

		files_to_remove = glob.glob( f"{molprob_output_dir}*" )
		cmd = ["rm", "-r"] + files_to_remove
		run_subprocess( cmd )

		return summary_dict


	def parallelize_molprobity_validation( self ):
		"""
		Perfom Molprobity validation on the given set of models in parallel.
		"""
		with Pool( self.cores ) as p:
			for result in p.imap_unordered( self.validate, self.model_ids ):
				summary_dict = result

				self.molprob_val_dict.update( summary_dict )


	def get_molprobity_validation_summary( self, output_dir: str
										) -> Dict[str, float]:
		"""
		Molprobity can provide detailed information about:
			Ramachandran outliers
						favored
			Rotamer outliers
			C-beta deviations
			Clashscore
			RMS(bonds)
			RMS(angles)
			MolProbity score
			Resolution
			R-work
			R-free
			Refinement program
		All this can be obtained from the *.out file generated by molprobity.
		"""
		with open( f"{output_dir}.out", "r" ) as f:
			summary = f.readlines()

		summary_dict = {}
		for i in range( len( summary ) ):
			line = summary[i]
			if "Summary" in line:
				for j in range( i+1, len( summary ) ):
					l = summary[j]

					split_line = l.strip().split( " = " )
					if len( split_line ) < 2:
						continue

					key, value = split_line 
					key = "".join( key.split( "  " ) )
					value = "".join( value.split( "  " ) )

					# Remove spaces from the end.
					key = key[:-1] if key[-1] == " " else key
					# Remove '%' symbols.
					value = value.replace( "%", "" )
					
					if value.isalpha():
						summary_dict[key] = value
					else:
						summary_dict[key] = float( value )

		return summary_dict


	def run_molprobity( self, model_file: str, output_dir: str ) -> None:
		"""
		Run Molprobity validation using Phenix.
		requires a PDB file with just 1 model.
		Generates the following files:
			{prefix}_coot.py  {prefix}.out  {prefix}.pkl  {prefix}.txt

		output_dir --> must be in the format "/path/prefix".
			where path is the output directory path and prefix is the 
				name for the output files generated.
		"""
		molprob_cmd = [
						"phenix.molprobity",
						f"{model_file}",
						f"output.prefix={output_dir}"
						]

		run_subprocess( molprob_cmd )

